// Comprehensive Icon Mapping for Ops Center - Official Logos
// Sources: GitHub repos, SimpleIcons CDN, official websites, DevIcons

export const appIconMap = {
    // === VIRTUALIZATION & CONTAINERS ===
    'proxmox-ve': 'https://www.proxmox.com/images/proxmox/Proxmox_symbol_standard_hex_400px.png',
    'portainer': 'https://cdn.simpleicons.org/portainer/13BEF9',
    'docker-swarm': 'https://cdn.simpleicons.org/docker/2496ED',
    'kubernetes': 'https://cdn.simpleicons.org/kubernetes/326CE5',
    'rancher': 'https://cdn.simpleicons.org/rancher/0075A8',
    'yacht': 'https://cdn.simpleicons.org/docker/2496ED',
    'dockge': 'https://raw.githubusercontent.com/louislam/dockge/master/frontend/public/icon.svg',
    'podman-desktop': 'https://cdn.simpleicons.org/podman/892CA0',
    'lxc-web-panel': 'https://cdn.simpleicons.org/linux/FCC624',
    'xcp-ng': 'https://xcp-ng.org/assets/img/logo.png',
    'xen-orchestra': 'https://xcp-ng.org/assets/img/logo.png',
    'openstack': 'https://cdn.simpleicons.org/openstack/ED1944',
    'nomad': 'https://cdn.simpleicons.org/nomad/00CA8E',
    'harvester': 'https://harvesterhci.io/img/harvester-logo.svg',
    'microk8s': 'https://cdn.simpleicons.org/kubernetes/326CE5',
    'k3s': 'https://cdn.simpleicons.org/k3s/FFC61C',
    'k9s': 'https://cdn.simpleicons.org/kubernetes/326CE5',
    'lazydocker': 'https://cdn.simpleicons.org/docker/2496ED',
    'casaos': 'https://raw.githubusercontent.com/IceWhaleTech/CasaOS/main/build/sysroot/usr/share/casaos/ui/assets/logo.svg',
    'umbrel': 'https://github.com/getumbrel/umbrel/raw/master/packages/ui/public/logo.svg',
    'startos': 'https://start9.com/latest/img/logo.png',
    'cosmos-server': 'https://cosmos-cloud.io/images/logo.png',
    'tipi': 'https://github.com/runtipi/runtipi/raw/master/src/client/public/logo.png',
    'runtipi': 'https://github.com/runtipi/runtipi/raw/master/src/client/public/logo.png',
    'caprover': 'https://caprover.com/img/logo.png',
    'coolify': 'https://cdn.simpleicons.org/coolify/6B46FF',
    'dokku': 'https://cdn.simpleicons.org/dokku/3A5FCD',
    'dozzle': 'https://dozzle.dev/assets/logo.png',
    'kasm-workspaces': 'https://kasmweb.com/assets/images/kasm-logo.png',
    'minecraft-server': 'https://cdn.simpleicons.org/minecraft/62B47A',
    'valheim-server': 'https://cdn.simpleicons.org/steam/000000',
    'palworld-server': 'https://cdn.simpleicons.org/steam/000000',
    'pterodactyl': 'https://pterodactyl.io/favicons/android-chrome-192x192.png',

    // === INFRASTRUCTURE MANAGEMENT ===
    'guacamole': 'https://guacamole.apache.org/images/logo-guac-lb.png',
    'rustdesk': 'https://rustdesk.com/images/logo.svg',
    'meshcentral': 'https://meshcentral.com/images/icon256.png',
    'remotely': 'https://cdn.simpleicons.org/microsoft/5E5E5E',
    'webmin': 'https://www.webmin.com/images/webmin-blue.png',
    'cockpit': 'https://cdn.simpleicons.org/redhat/EE0000',
    'ajenti': 'https://cdn.simpleicons.org/linux/FCC624',
    'tinypilot': 'https://tinypilotkvm.com/favicon.svg',
    'pikvm': 'https://pikvm.org/favicon.png',
    'homepage': 'https://gethomepage.dev/logo.png',
    'homarr': 'https://homarr.dev/imgs/logo.png',
    'heimdall': 'https://cdn.simpleicons.org/heimdall/000000',
    'dashy': 'https://dashy.to/img/dashy.png',
    'organizr': 'https://github.com/causefx/Organizr/raw/v2-master/plugins/images/organizr/logo-no-border.png',
    'flame': 'https://cdn.simpleicons.org/firefoxbrowser/FF7139',
    'fenrus': 'https://cdn.simpleicons.org/linux/FCC624',
    'glance': 'https://cdn.simpleicons.org/googlechrome/4285F4',
    'olivetin': 'https://www.olivetin.app/images/icons/OliveTinLogo.png',
    'rundeck': 'https://cdn.simpleicons.org/rundeck/F73C3C',
    'ansible-semaphore': 'https://cdn.simpleicons.org/ansible/EE0000',
    'awx': 'https://cdn.simpleicons.org/ansible/EE0000',
    'it-tools': 'https://it-tools.tech/favicon.svg',
    'cyberchef': 'https://gchq.github.io/CyberChef/images/cyberchef.svg',
    'stirling-pdf': 'https://cdn.simpleicons.org/adobeacrobatreader/EC1C24',
    'paperless-ngx': 'https://docs.paperless-ngx.com/assets/favicon.png',
    'wiki-js': 'https://cdn.simpleicons.org/wikidotjs/1976D2',
    'bookstack': 'https://cdn.simpleicons.org/bookstack/0288D1',
    'dokuwiki': 'https://cdn.simpleicons.org/wikipedia/000000',
    'joplin-server': 'https://cdn.simpleicons.org/joplin/1071D3',
    'trilium-notes': 'https://github.com/zadam/trilium/raw/master/src/public/images/app-icons/png/256x256.png',
    'outline': 'https://cdn.simpleicons.org/outline/42A5F5',
    'snipe-it': 'https://snipeitapp.com/img/favicon.png',
    'netbox': 'https://raw.githubusercontent.com/netbox-community/netbox/develop/netbox/project-static/img/netbox_icon.svg',
    'phpipam': 'https://phpipam.net/css/images/logo.png',
    'racktables': 'https://cdn.simpleicons.org/databricks/FF3621',
    'cachet': 'https://cachethq.io/img/cachet-logo.svg',
    'statping': 'https://cdn.simpleicons.org/statuspage/FF6F00',
    'upptime': 'https://upptime.js.org/img/icon.svg',
    'code-server': 'https://cdn.simpleicons.org/visualstudiocode/007ACC',
    'jupyterhub': 'https://cdn.simpleicons.org/jupyter/F37626',
    'ghost': 'https://cdn.simpleicons.org/ghost/15171A',
    'wordpress': 'https://cdn.simpleicons.org/wordpress/21759B',
    'mattermost': 'https://cdn.simpleicons.org/mattermost/0058CC',
    'rocket-chat': 'https://cdn.simpleicons.org/rocketdotchat/F5455C',

    // === NETWORK MONITORING ===
    'uptime-kuma': 'https://uptime.kuma.pet/img/icon.svg',
    'nagios': 'https://cdn.simpleicons.org/nagios/000000',
    'zabbix': 'https://cdn.simpleicons.org/zabbix/D40000',
    'librenms': 'https://www.librenms.org/img/librenms.svg',
    'observium': 'https://www.observium.org/images/observium-logo.png',
    'checkmk': 'https://checkmk.com/themes/facelift/images/tribe29_logo.svg',
    'icinga-2': 'https://cdn.simpleicons.org/icinga/06062C',
    'prometheus': 'https://cdn.simpleicons.org/prometheus/E6522C',
    'grafana': 'https://cdn.simpleicons.org/grafana/F46800',
    'netdata': 'https://cdn.simpleicons.org/netdata/00AB44',
    'glances': 'https://nicolargo.github.io/glances/images/header-logo.png',
    'beszel': 'https://cdn.simpleicons.org/datadog/632CA6',
    'cacti': 'https://www.cacti.net/images/logo.svg',
    'smokeping': 'https://oss.oetiker.ch/smokeping/img/smokeping.png',
    'pingvin': 'https://cdn.simpleicons.org/pingdom/FFF000',
    'gatus': 'https://gatus.io/logo.svg',
    'blackbox-exporter': 'https://cdn.simpleicons.org/prometheus/E6522C',
    'node-exporter': 'https://cdn.simpleicons.org/prometheus/E6522C',
    'cadvisor': 'https://cdn.simpleicons.org/googlecontaineroptimizedos/4285F4',
    'influxdb': 'https://cdn.simpleicons.org/influxdb/22ADF6',
    'victoriametrics': 'https://docs.victoriametrics.com/logo.png',
    'loki': 'https://grafana.com/static/img/logos/logo-loki.svg',
    'graylog': 'https://cdn.simpleicons.org/graylog/FF3633',
    'elk-stack': 'https://cdn.simpleicons.org/elastic/005571',
    'splunk': 'https://cdn.simpleicons.org/splunk/000000',

    // === SECURITY & FIREWALL ===
    'wazuh': 'https://wazuh.com/uploads/2022/05/logo-blue-h.svg',
    'security-onion': 'https://cdn.simpleicons.org/linux/FCC624',
    'pfsense': 'https://cdn.simpleicons.org/pfsense/212121',
    'opnsense': 'https://opnsense.org/wp-content/themes/OPNsense/assets/img/opnsense.png',
    'openwrt': 'https://cdn.simpleicons.org/openwrt/00B5E2',
    'pi-hole': 'https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/cropped-Vortex-R.png',
    'adguard-home': 'https://cdn.simpleicons.org/adguard/68BC71',
    'technitium': 'https://technitium.com/img/logo.png',
    'nginx-proxy-manager': 'https://nginxproxymanager.com/icon.png',
    'traefik': 'https://cdn.simpleicons.org/traefikproxy/24A1C1',
    'caddy': 'https://cdn.simpleicons.org/caddy/1F88C0',
    'haproxy': 'https://cdn.simpleicons.org/haproxy/35495E',
    'swag': 'https://cdn.simpleicons.org/letsencrypt/003A70',
    'authelia': 'https://www.authelia.com/images/branding/logo-cropped.png',
    'authentik': 'https://goauthentik.io/img/icon.png',
    'keycloak': 'https://cdn.simpleicons.org/keycloak/4D4D4D',
    'vaultwarden': 'https://cdn.simpleicons.org/bitwarden/175DDC',
    'bitwarden': 'https://cdn.simpleicons.org/bitwarden/175DDC',
    'passbolt': 'https://cdn.simpleicons.org/passbolt/D40000',
    'wireguard-easy': 'https://cdn.simpleicons.org/wireguard/88171A',
    'openvpn-as': 'https://cdn.simpleicons.org/openvpn/EA7E20',
    'tailscale': 'https://cdn.simpleicons.org/tailscale/000000',
    'headscale': 'https://cdn.simpleicons.org/tailscale/000000',
    'netbird': 'https://netbird.io/img/logo.svg',
    'firezone': 'https://cdn.simpleicons.org/fireship/FF6D00',
    'zerotier': 'https://cdn.simpleicons.org/zerotier/FFB441',
    'crowdsec': 'https://www.crowdsec.net/wp-content/uploads/2022/01/crowdsec-logo.png',
    'frigate': 'https://frigate.video/img/frigate.png',
    'blue-iris': 'https://cdn.simpleicons.org/camera/000000',
    'zoneminder': 'https://zoneminder.com/img/icons/apple-touch-icon-152x152.png',
    'shinobi': 'https://shinobi.video/libs/assets/icon/apple-icon-180x180.png',
    'agent-dvr': 'https://cdn.simpleicons.org/camera/000000',
    'motioneye': 'https://cdn.simpleicons.org/camera/000000',

    // === DATA STORAGE & BACKUP ===
    'truenas-scale': 'https://www.truenas.com/docs/images/TrueNAS-Logo1.png',
    'truenas-core': 'https://www.truenas.com/docs/images/TrueNAS-Logo1.png',
    'unraid': 'https://cdn.simpleicons.org/unraid/F15A2C',
    'openmediavault': 'https://www.openmediavault.org/images/logo.svg',
    'synology-dsm': 'https://cdn.simpleicons.org/synology/B5B5B6',
    'nextcloud': 'https://cdn.simpleicons.org/nextcloud/0082C9',
    'owncloud': 'https://cdn.simpleicons.org/owncloud/1D2D44',
    'seafile': 'https://www.seafile.com/media/img/seafile-logo.png',
    'filebrowser': 'https://filebrowser.org/img/logo.svg',
    'syncthing': 'https://cdn.simpleicons.org/syncthing/0891D1',
    'resilio-sync': 'https://cdn.simpleicons.org/resilio/1E88BD',
    'duplicati': 'https://www.duplicati.com/img/logo.png',
    'duplicacy': 'https://duplicacy.com/logo.png',
    'urbackup': 'https://cdn.simpleicons.org/databricks/FF3621',
    'kopia': 'https://kopia.io/favicon.png',
    'minio': 'https://cdn.simpleicons.org/minio/C72E49',
    'ceph': 'https://cdn.simpleicons.org/ceph/EF5C55',
    'longhorn': 'https://longhorn.io/img/logos/longhorn-icon-color.png',
    'plex': 'https://cdn.simpleicons.org/plex/EBAF00',
    'jellyfin': 'https://cdn.simpleicons.org/jellyfin/00A4DC',
    'emby': 'https://cdn.simpleicons.org/emby/52B54B',
    'navidrome': 'https://www.navidrome.org/favicon.svg',
    'audiobookshelf': 'https://www.audiobookshelf.org/Logo.png',
    'immich': 'https://immich.app/img/immich-logo.svg',
    'photoprism': 'https://cdn.simpleicons.org/photoprism/96BC33',
    'librephotos': 'https://cdn.simpleicons.org/photograph/000000',
    'lychee': 'https://lycheeorg.github.io/img/logo.png',
    'piwigo': 'https://piwigo.org/favicon.ico',
    'mariadb': 'https://cdn.simpleicons.org/mariadb/003545',
    'postgresql': 'https://cdn.simpleicons.org/postgresql/4169E1',
    'mysql': 'https://cdn.simpleicons.org/mysql/4479A1',
    'redis': 'https://cdn.simpleicons.org/redis/DC382D',
    'mongodb': 'https://cdn.simpleicons.org/mongodb/47A248',
    'adminer': 'https://www.adminer.org/static/logo.png',
    'phpmyadmin': 'https://cdn.simpleicons.org/phpmyadmin/6C78AF',
    'pgadmin': 'https://cdn.simpleicons.org/postgresql/4169E1',

    // === AUTOMATION & ORCHESTRATION ===
    'home-assistant': 'https://cdn.simpleicons.org/homeassistant/41BDF5',
    'node-red': 'https://cdn.simpleicons.org/nodered/8F0000',
    'n8n': 'https://cdn.simpleicons.org/n8n/EA4B71',
    'huginn': 'https://cdn.simpleicons.org/github/181717',
    'openhab': 'https://cdn.simpleicons.org/openhab/E64910',
    'domoticz': 'https://www.domoticz.com/DomoticzLogoOnly.png',
    'esphome': 'https://cdn.simpleicons.org/esphome/000000',
    'mosquitto': 'https://mosquitto.org/images/mosquitto-text-side-28.png',
    'emqx': 'https://www.emqx.io/static/img/logo.svg',
    'zigbee2mqtt': 'https://www.zigbee2mqtt.io/images/logo.png',
    'z-wave-js-ui': 'https://cdn.simpleicons.org/z-wave/CC0000',
    'homebridge': 'https://cdn.simpleicons.org/homebridge/491F59',
    'gitlab': 'https://cdn.simpleicons.org/gitlab/FC6D26',
    'gitea': 'https://cdn.simpleicons.org/gitea/609926',
    'forgejo': 'https://cdn.simpleicons.org/forgejo/FB923C',
    'gogs': 'https://cdn.simpleicons.org/go/00ADD8',
    'jenkins': 'https://cdn.simpleicons.org/jenkins/D24939',
    'drone': 'https://cdn.simpleicons.org/drone/212121',
    'argocd': 'https://cdn.simpleicons.org/argo/EF7B4D',
    'radarr': 'https://radarr.video/img/logo.png',
    'sonarr': 'https://sonarr.tv/img/logo.png',
    'lidarr': 'https://lidarr.audio/img/logo.png',
    'readarr': 'https://readarr.com/img/logo.png',
    'bazarr': 'https://www.bazarr.media/assets/img/logo.png',
    'prowlarr': 'https://prowlarr.com/img/logo.png',
    'whisparr': 'https://cdn.simpleicons.org/plex/EBAF00',
    'jackett': 'https://cdn.simpleicons.org/jackett/52B54B',
    'overseerr': 'https://overseerr.dev/os_logo_square.svg',
    'jellyseerr': 'https://cdn.simpleicons.org/jellyfin/00A4DC',
    'ombi': 'https://cdn.simpleicons.org/plex/EBAF00',
    'tdarr': 'https://tdarr.io/img/logo.png',
    'unmanic': 'https://cdn.simpleicons.org/convertio/FF6900',
    'fileflows': 'https://cdn.simpleicons.org/files/000000',
    'sabnzbd': 'https://sabnzbd.org/images/logo-full.svg',
    'nzbget': 'https://cdn.simpleicons.org/nzxt/000000',
    'qbittorrent': 'https://cdn.simpleicons.org/qbittorrent/2F67BA',
    'transmission': 'https://cdn.simpleicons.org/transmission/B62828',
    'deluge': 'https://cdn.simpleicons.org/deluge/3A64F6',
    'rtorrent': 'https://cdn.simpleicons.org/rtorrent/000000',
    'flood': 'https://cdn.simpleicons.org/flood/00A3E0',
    'cloudflare-tunnel': 'https://cdn.simpleicons.org/cloudflare/F38020',

    // === PERFORMANCE ANALYTICS ===
    'ollama': 'https://cdn.simpleicons.org/ollama/000000',
    'open-webui': 'https://cdn.simpleicons.org/openai/412991',
    'localai': 'https://cdn.simpleicons.org/ai/FF6F00',
    'stable-diffusion': 'https://cdn.simpleicons.org/stablediffusion/000000',
    'tautulli': 'https://tautulli.com/images/logo.png',
    'varys': 'https://cdn.simpleicons.org/plex/EBAF00',
    'goaccess': 'https://goaccess.io/images/goaccess-logo.png',
    'plausible': 'https://cdn.simpleicons.org/plausibleanalytics/5850EC',
    'matomo': 'https://cdn.simpleicons.org/matomo/3152A0',
    'umami': 'https://cdn.simpleicons.org/umami/000000',
    'posthog': 'https://cdn.simpleicons.org/posthog/000000',
    'sentry': 'https://cdn.simpleicons.org/sentry/362D59',
    'speedtest-tracker': 'https://cdn.simpleicons.org/speedtest/141526',
    'librespeed': 'https://cdn.simpleicons.org/speedtest/141526',
    'ntopng': 'https://www.ntop.org/wp-content/uploads/2011/08/logo_full.png',
    'arkime': 'https://arkime.com/assets/Arkime_Logo_FullGradient.png',
    'malcolm': 'https://cdn.simpleicons.org/security/000000',
    'healthchecks': 'https://healthchecks.io/static/img/logo.svg',
    'changedetection': 'https://cdn.simpleicons.org/detect/00B4D8',
    'selenium': 'https://cdn.simpleicons.org/selenium/43B02A',
    'k6': 'https://cdn.simpleicons.org/k6/7D64FF',
    'locust': 'https://cdn.simpleicons.org/locust/000000',
    'jmeter': 'https://cdn.simpleicons.org/apachejmeter/D22128',
    'pyroscope': 'https://cdn.simpleicons.org/pyroscope/000000',
    'parca': 'https://cdn.simpleicons.org/databricks/FF3621',
    'signoz': 'https://signoz.io/img/SigNozLogo-orange.svg',
    'jaeger': 'https://cdn.simpleicons.org/jaeger/66CFE3',
    'zipkin': 'https://cdn.simpleicons.org/zipkin/000000',
    'tempo': 'https://grafana.com/static/img/logos/logo-tempo.svg',
    'mimir': 'https://grafana.com/static/img/logos/logo-mimir.svg',
    'thanos': 'https://cdn.simpleicons.org/thanos/6C42E5',
    'fluentd': 'https://cdn.simpleicons.org/fluentd/0E83C8',
    'fluent-bit': 'https://cdn.simpleicons.org/fluentbit/49BDA5',
    'vector': 'https://cdn.simpleicons.org/vector/0DAC8C',
    'logstash': 'https://cdn.simpleicons.org/logstash/005571'
};

// Category-based default icons (Lucide icon names as fallback)
export const categoryDefaultIcons = {
    'infrastructure': 'Server',
    'monitoring': 'Activity',
    'security': 'Shield',
    'storage': 'Database',
    'virtualization': 'Box',
    'automation': 'Workflow',
    'analytics': 'BarChart3'
};

// Helper function to get icon for an app
// Returns either a CDN URL string or a Lucide icon name string
export const getAppIcon = (appId, category) => {
    // First, check if we have a specific icon mapped for this app
    if (appIconMap[appId]) {
        return appIconMap[appId];
    }

    // If not, use category default
    if (category && categoryDefaultIcons[category]) {
        return categoryDefaultIcons[category];
    }

    // Final fallback
    return 'Server';
};
