import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

//Translation resources for 6 languages: Hindi, English, Russian, French, Dutch, Korean
const resources = {
    hi: {
        translation: {
            "sidebar": { "dashboard": "डैशबोर्ड", "services": "सेवाएं", "docker": "डॉकर प्रबंधक", "monitoring": "निगरानी", "terminal": "SSH टर्मिनल", "rdp": "RDP लॉन्चर", "topology": "संचालन केंद्र", "appStore": "ऐप स्टोर", "settings": "सेटिंग्स", "logout": "लॉगआउट" },
            "login": { "welcome": "वापसी पर स्वागत है", "subtitle": "डल्लाल डैशबोर्ड जारी रखने के लिए साइन इन करें", "username": "उपयोगकर्ता नाम", "password": "पासवर्ड", "signin": "साइन इन करें" },
            "dashboard": { "overview": { "title": "डैशबोर्ड अवलोकन", "subtitle": "अपने बुनियादी ढांचे की एक नज़र में निगरानी करें", "serviceStatus": "सेवा स्थिति", "totalServices": "कुल सेवाएं", "online": "ऑनलाइन", "offline": "ऑफलाइन", "alerts": "अलर्ट", "critical": "गंभीर", "warnings": "चेतावनियां", "recentAlerts": "हाल के अलर्ट", "viewAll": "सभी अलर्ट देखें", "uptime": "सिस्टम अपटाइम", "trend": "रुझान" }, "favorites": { "title": "पसंदीदा सेवाएं", "subtitle": "आपकी पिन की गई सेवाओं तक त्वरित पहुंच", "empty": "अभी तक कोई पसंदीदा सेवा नहीं", "emptyHint": "उन्हें यहां जोड़ने के लिए सेवाएं पृष्ठ से सेवाओं को स्टार करें" } },
            "docker": { "title": "डॉकर प्रबंधक", "subtitle": "डॉकर कंटेनर और सेवाओं का प्रबंधन करें", "daemon": "डॉकर डेमन", "status": "स्थिति", "running": "चल रहा है", "stopped": "रुका हुआ", "containers": "कंटेनर", "images": "इमेजेज", "version": "संस्करण", "notDetected": "डॉकर नहीं मिला", "notDetectedMsg": "डॉकर इंजन चल नहीं रहा है या इंस्टॉल नहीं है", "retry": "कनेक्शन पुनः प्रयास करें", "actions": { "start": "शुरू करें", "stop": "रोकें", "restart": "पुनः आरंभ करें", "logs": "लॉग देखें" }, "logsTitle": "कंटेनर लॉग" },
            "monitoring": { "metrics": { "title": "ऐतिहासिक मेट्रिक्स", "subtitle": "समय के साथ सेवा प्रदर्शन देखें", "selectService": "एक सेवा चुनें", "dateRange": "तिथि सीमा", "last24h": "पिछले 24 घंटे", "last7d": "पिछले 7 दिन", "last30d": "पिछले 30 दिन", "avgResponseTime": "औसत प्रतिक्रिया समय", "minResponseTime": "न्यूनतम प्रतिक्रिया समय", "maxResponseTime": "अधिकतम प्रतिक्रिया समय", "uptimePercentage": "अपटाइम", "dataPoints": "डेटा पॉइंट्स", "responseTime": "प्रतिक्रिया समय", "availability": "उपलब्धता स्थिति" }, "alerts": { "title": "अलर्ट लॉग", "subtitle": "सिस्टम अलर्ट की निगरानी और प्रबंधन करें", "severity": "गंभीरता", "status": "स्थिति", "all": "सभी", "critical": "गंभीर", "warning": "चेतावनी", "info": "जानकारी", "active": "सक्रिय", "resolved": "हल हो गया", "search": "अलर्ट खोजें...", "totalAlerts": "कुल अलर्ट", "criticalAlerts": "गंभीर", "warningAlerts": "चेतावनियां", "activeAlerts": "सक्रिय", "resolvedAlerts": "हल हो गए", "acknowledge": "स्वीकार करें", "resolve": "हल करें", "details": "अलर्ट विवरण" } },
            "ssh": { "console": { "title": "SSH कंसोल", "subtitle": "SSH के माध्यम से दूरस्थ सर्वर से कनेक्ट करें", "selectService": "एक सेवा चुनें", "connect": "कनेक्ट करें", "disconnect": "डिस्कनेक्ट करें", "connected": "कनेक्टेड", "disconnected": "डिस्कनेक्टेड" }, "history": { "title": "कमांड इतिहास", "subtitle": "सभी निष्पादित SSH कमांड को ट्रैक और समीक्षा करें", "totalCommands": "कुल कमांड", "successful": "सफल", "failed": "विफल", "services": "सेवाएं", "time": "समय", "service": "सेवा", "user": "उपयोगकर्ता", "command": "कमांड", "status": "स्थिति", "duration": "अवधि", "noCommands": "आपके फ़िल्टर से मेल खाने वाला कोई कमांड नहीं" }, "sftp": { "title": "SFTP ब्राउज़र", "subtitle": "दूरस्थ सर्वर पर फ़ाइलें ब्राउज़ करें और प्रबंधित करें", "server": "सर्वर", "username": "उपयोगकर्ता नाम", "password": "पासवर्ड", "connect": "कनेक्ट करें", "disconnect": "डिस्कनेक्ट करें", "connected": "कनेक्टेड", "name": "नाम", "size": "आकार", "modified": "संशोधित", "permissions": "अनुमतियां", "actions": "क्रियाएं", "download": "डाउनलोड करें", "delete": "हटाएं" } },
            "rdp": { "sessions": { "title": "RDP सत्र", "subtitle": "रिमोट डेस्कटॉप प्रोटोकॉल कनेक्शन लॉन्च और प्रबंधित करें", "newConnection": "नया RDP कनेक्शन", "server": "सर्वर", "username": "उपयोगकर्ता नाम", "password": "पासवर्ड", "resolution": "रेज़ोल्यूशन", "colorDepth": "रंग गहराई", "connect": "कनेक्ट करें", "download": ".rdp फ़ाइल डाउनलोड करें", "activeSessions": "सक्रिय सत्र", "noSessions": "कोई सक्रिय RDP सत्र नहीं", "user": "उपयोगकर्ता", "duration": "अवधि", "disconnect": "डिस्कनेक्ट करें", "connected": "कनेक्टेड" }, "recordings": { "title": "स्क्रीन रिकॉर्डिंग", "subtitle": "रिकॉर्ड किए गए RDP सत्रों को देखें और प्रबंधित करें", "totalRecordings": "कुल रिकॉर्डिंग", "totalDuration": "कुल अवधि", "storageUsed": "उपयोग किया गया स्टोरेज", "session": "सत्र", "service": "सेवा", "dateTime": "तिथि और समय", "duration": "अवधि", "size": "आकार", "actions": "क्रियाएं", "play": "चलाएं", "download": "डाउनलोड करें", "delete": "हटाएं", "noRecordings": "आपके फ़िल्टर से मेल खाने वाली कोई रिकॉर्डिंग नहीं" } },
            "common": { "online": "ऑनलाइन", "offline": "ऑफलाइन", "loading": "लोड हो रहा है...", "save": "सहेजें", "cancel": "रद्द करें", "delete": "हटाएं", "edit": "संपादित करें", "search": "खोजें", "filter": "फ़िल्टर करें", "actions": "क्रियाएं", "status": "स्थिति", "name": "नाम", "close": "बंद करें", "success": "सफलता", "error": "त्रुटि", "warning": "चेतावनी", "info": "जानकारी" }
        }
    },
    en: {
        translation: {
            "sidebar": { "dashboard": "Dashboard", "services": "Services", "docker": "Docker Manager", "monitoring": "Monitoring", "terminal": "SSH Terminal", "rdp": "RDP Launcher", "topology": "Ops Center", "appStore": "App Store", "settings": "Settings", "logout": "Logout" },
            "login": { "welcome": "Welcome Back", "subtitle": "Sign in to continue to Dallal Dashboard", "username": "Username", "password": "Password", "signin": "Sign In" },
            "dashboard": { "overview": { "title": "Dashboard Overview", "subtitle": "Monitor your infrastructure at a glance", "serviceStatus": "Service Status", "totalServices": "Total Services", "online": "Online", "offline": "Offline", "alerts": "Alerts", "critical": "Critical", "warnings": "Warnings", "recentAlerts": "Recent Alerts", "viewAll": "View All Alerts", "uptime": "System Uptime", "trend": "Trend" }, "favorites": { "title": "Favorite Services", "subtitle": "Quick access to your pinned services", "empty": "No favorite services yet", "emptyHint": "Star services from the Services page to add them here" } },
            "docker": { "title": "Docker Manager", "subtitle": "Manage Docker containers and services", "daemon": "Docker Daemon", "status": "Status", "running": "Running", "stopped": "Stopped", "containers": "Containers", "images": "Images", "version": "Version", "notDetected": "Docker Not Detected", "notDetectedMsg": "Docker Engine is not running or not installed", "retry": "Retry Connection", "actions": { "start": "Start", "stop": "Stop", "restart": "Restart", "logs": "View Logs" }, "logsTitle": "Container Logs" },
            "monitoring": { "metrics": { "title": "Historical Metrics", "subtitle": "View service performance over time", "selectService": "Select a service", "dateRange": "Date Range", "last24h": "Last 24 Hours", "last7d": "Last 7 Days", "last30d": "Last 30 Days", "avgResponseTime": "Avg Response Time", "minResponseTime": "Min Response Time", "maxResponseTime": "Max Response Time", "uptimePercentage": "Uptime", "dataPoints": "Data Points", "responseTime": "Response Time", "availability": "Availability Status" }, "alerts": { "title": "Alerts Log", "subtitle": "Monitor and manage system alerts", "severity": "Severity", "status": "Status", "all": "All", "critical": "Critical", "warning": "Warning", "info": "Info", "active": "Active", "resolved": "Resolved", "search": "Search alerts...", "totalAlerts": "Total Alerts", "criticalAlerts": "Critical", "warningAlerts": "Warnings", "activeAlerts": "Active", "resolvedAlerts": "Resolved", "acknowledge": "Acknowledge", "resolve": "Resolve", "details": "Alert Details" } },
            "ssh": { "console": { "title": "SSH Console", "subtitle": "Connect to remote servers via SSH", "selectService": "Select a service", "connect": "Connect", "disconnect": "Disconnect", "connected": "Connected", "disconnected": "Disconnected" }, "history": { "title": "Command History", "subtitle": "Track and review all SSH commands executed", "totalCommands": "Total Commands", "successful": "Successful", "failed": "Failed", "services": "Services", "time": "Time", "service": "Service", "user": "User", "command": "Command", "status": "Status", "duration": "Duration", "noCommands": "No commands match your filters" }, "sftp": { "title": "SFTP Browser", "subtitle": "Browse and manage files on remote servers", "server": "Server", "username": "Username", "password": "Password", "connect": "Connect", "disconnect": "Disconnect", "connected": "Connected", "name": "Name", "size": "Size", "modified": "Modified", "permissions": "Permissions", "actions": "Actions", "download": "Download", "delete": "Delete" } },
            "rdp": { "sessions": { "title": "RDP Sessions", "subtitle": "Launch and manage Remote Desktop Protocol connections", "newConnection": "New RDP Connection", "server": "Server", "username": "Username", "password": "Password", "resolution": "Resolution", "colorDepth": "Color Depth", "connect": "Connect", "download": "Download .rdp File", "activeSessions": "Active Sessions", "noSessions": "No active RDP sessions", "user": "User", "duration": "Duration", "disconnect": "Disconnect", "connected": "Connected" }, "recordings": { "title": "Screen Recordings", "subtitle": "View and manage recorded RDP sessions", "totalRecordings": "Total Recordings", "totalDuration": "Total Duration", "storageUsed": "Storage Used", "session": "Session", "service": "Service", "dateTime": "Date & Time", "duration": "Duration", "size": "Size", "actions": "Actions", "play": "Play", "download": "Download", "delete": "Delete", "noRecordings": "No recordings match your filters" } },
            "common": { "online": "Online", "offline": "Offline", "loading": "Loading...", "save": "Save", "cancel": "Cancel", "delete": "Delete", "edit": "Edit", "search": "Search", "filter": "Filter", "actions": "Actions", "status": "Status", "name": "Name", "close": "Close", "success": "Success", "error": "Error", "warning": "Warning", "info": "Info" }
        }
    },
    ru: {
        translation: {
            "sidebar": { "dashboard": "Панель", "services": "Сервисы", "docker": "Docker Manager", "monitoring": "Мониторинг", "terminal": "SSH-терминал", "rdp": "RDP Launcher", "topology": "Операционный центр", "appStore": "Магазин приложений", "settings": "Настройки", "logout": "Выйти" },
            "login": { "welcome": "Добро пожаловать", "subtitle": "Войдите, чтобы продолжить", "username": "Имя пользователя", "password": "Пароль", "signin": "Войти" },
            "dashboard": { "overview": { "title": "Обзор панели", "subtitle": "Мониторинг инфраструктуры одним взглядом", "serviceStatus": "Статус сервиса", "totalServices": "Всего сервисов", "online": "Онлайн", "offline": "Оффлайн", "alerts": "Оповещения", "critical": "Критические", "warnings": "Предупреждения", "recentAlerts": "Недавние оповещения", "viewAll": "Посмотреть все", "uptime": "Время работы", "trend": "Тренд" }, "favorites": { "title": "Избранные сервисы", "subtitle": "Быстрый доступ к закрепленным сервисам", "empty": "Пока нет избранных", "emptyHint": "Отметьте сервисы на странице Сервисы" } },
            "docker": { "title": "Docker Manager", "subtitle": "Управление Docker-контейнерами", "daemon": "Docker Daemon", "status": "Статус", "running": "Запущен", "stopped": "Остановлен", "containers": "Контейнеры", "images": "Образы", "version": "Версия", "notDetected": "Docker не обнаружен", "notDetectedMsg": "Docker Engine не запущен или не установлен", "retry": "Повторить подключение", "actions": { "start": "Запустить", "stop": "Остановить", "restart": "Перезапустить", "logs": "Просмотр логов" }, "logsTitle": "Логи контейнера" },
            "monitoring": { "metrics": { "title": "Исторические метрики", "subtitle": "Просмотр производительности сервиса", "selectService": "Выберите сервис", "dateRange": "Диапазон дат", "last24h": "Последние 24 часа", "last7d": "Последние 7 дней", "last30d": "Последние 30 дней", "avgResponseTime": "Среднее время отклика", "minResponseTime": "Мин. время отклика", "maxResponseTime": "Макс. время отклика", "uptimePercentage": "Время работы", "dataPoints": "Точки данных", "responseTime": "Время отклика", "availability": "Статус доступности" }, "alerts": { "title": "Журнал оповещений", "subtitle": "Мониторинг системных оповещений", "severity": "Серьезность", "status": "Статус", "all": "Все", "critical": "Критические", "warning": "Предупреждение", "info": "Инфо", "active": "Активные", "resolved": "Решенные", "search": "Поиск оповещений...", "totalAlerts": "Всего оповещений", "criticalAlerts": "Критические", "warningAlerts": "Предупреждения", "activeAlerts": "Активные", "resolvedAlerts": "Решенные", "acknowledge": "Подтвердить", "resolve": "Решить", "details": "Детали" } },
            "ssh": { "console": { "title": "SSH-консоль", "subtitle": "Подключение к удаленным серверам", "selectService": "Выберите сервис", "connect": "Подключить", "disconnect": "Отключить", "connected": "Подключено", "disconnected": "Отключено" }, "history": { "title": "История команд", "subtitle": "Отслеживание выполненных SSH-команд", "totalCommands": "Всего команд", "successful": "Успешные", "failed": "Неудачные", "services": "Сервисы", "time": "Время", "service": "Сервис", "user": "Пользователь", "command": "Команда", "status": "Статус", "duration": "Длительность", "noCommands": "Нет команд" }, "sftp": { "title": "SFTP-браузер", "subtitle": "Обзор файлов на удаленных серверах", "server": "Сервер", "username": "Имя пользователя", "password": "Пароль", "connect": "Подключить", "disconnect": "Отключить", "connected": "Подключено", "name": "Имя", "size": "Размер", "modified": "Изменено", "permissions": "Права", "actions": "Действия", "download": "Скачать", "delete": "Удалить" } },
            "rdp": { "sessions": { "title": "RDP-сессии", "subtitle": "Запуск удаленного рабочего стола", "newConnection": "Новое RDP-подключение", "server": "Сервер", "username": "Имя пользователя", "password": "Пароль", "resolution": "Разрешение", "colorDepth": "Глубина цвета", "connect": "Подключить", "download": "Скачать .rdp файл", "activeSessions": "Активные сессии", "noSessions": "Нет активных RDP-сессий", "user": "Пользователь", "duration": "Длительность", "disconnect": "Отключить", "connected": "Подключено" }, "recordings": { "title": "Записи экрана", "subtitle": "Просмотр записанных RDP-сессий", "totalRecordings": "Всего записей", "totalDuration": "Общая длительность", "storageUsed": "Использовано памяти", "session": "Сессия", "service": "Сервис", "dateTime": "Дата и время", "duration": "Длительность", "size": "Размер", "actions": "Действия", "play": "Воспроизвести", "download": "Скачать", "delete": "Удалить", "noRecordings": "Нет записей" } },
            "common": { "online": "Онлайн", "offline": "Оффлайн", "loading": "Загрузка...", "save": "Сохранить", "cancel": "Отмена", "delete": "Удалить", "edit": "Редактировать", "search": "Поиск", "filter": "Фильтр", "actions": "Действия", "status": "Статус", "name": "Имя", "close": "Закрыть", "success": "Успех", "error": "Ошибка", "warning": "Предупреждение", "info": "Инфо" }
        }
    },
    fr: {
        translation: {
            "sidebar": { "dashboard": "Tableau de bord", "services": "Services", "docker": "Gestionnaire Docker", "monitoring": "Surveillance", "terminal": "Terminal SSH", "rdp": "Lanceur RDP", "topology": "Centre des opérations", "appStore": "Boutique d'applications", "settings": "Paramètres", "logout": "Déconnexion" },
            "login": { "welcome": "Bienvenue", "subtitle": "Connectez-vous pour continuer vers Dallal Dashboard", "username": "Nom d'utilisateur", "password": "Mot de passe", "signin": "Se connecter" },
            "dashboard": { "overview": { "title": "Vue d'ensemble du tableau de bord", "subtitle": "Surveillez votre infrastructure en un coup d'œil", "serviceStatus": "État des services", "totalServices": "Total des services", "online": "En ligne", "offline": "Hors ligne", "alerts": "Alertes", "critical": "Critique", "warnings": "Avertissements", "recentAlerts": "Alertes récentes", "viewAll": "Voir toutes les alertes", "uptime": "Temps de disponibilité", "trend": "Tendance" }, "favorites": { "title": "Services favoris", "subtitle": "Accès rapide à vos services épinglés", "empty": "Aucun service favori pour le moment", "emptyHint": "Marquez des services depuis la page Services pour les ajouter ici" } },
            "docker": { "title": "Gestionnaire Docker", "subtitle": "Gérer les conteneurs et services Docker", "daemon": "Démon Docker", "status": "Statut", "running": "En cours d'exécution", "stopped": "Arrêté", "containers": "Conteneurs", "images": "Images", "version": "Version", "notDetected": "Docker non détecté", "notDetectedMsg": "Le moteur Docker n'est pas en cours d'exécution ou n'est pas installé", "retry": "Réessayer la connexion", "actions": { "start": "Démarrer", "stop": "Arrêter", "restart": "Redémarrer", "logs": "Voir les journaux" }, "logsTitle": "Journaux du conteneur" },
            "monitoring": { "metrics": { "title": "Métriques historiques", "subtitle": "Voir les performances du service au fil du temps", "selectService": "Sélectionnez un service", "dateRange": "Plage de dates", "last24h": "Dernières 24 heures", "last7d": "7 derniers jours", "last30d": "30 derniers jours", "avgResponseTime": "Temps de réponse moyen", "minResponseTime": "Temps de réponse minimum", "maxResponseTime": "Temps de réponse maximum", "uptimePercentage": "Disponibilité", "dataPoints": "Points de données", "responseTime": "Temps de réponse", "availability": "État de disponibilité" }, "alerts": { "title": "Journal des alertes", "subtitle": "Surveiller et gérer les alertes système", "severity": "Gravité", "status": "Statut", "all": "Tous", "critical": "Critique", "warning": "Avertissement", "info": "Info", "active": "Actif", "resolved": "Résolu", "search": "Rechercher des alertes...", "totalAlerts": "Total des alertes", "criticalAlerts": "Critiques", "warningAlerts": "Avertissements", "activeAlerts": "Actives", "resolvedAlerts": "Résolues", "acknowledge": "Accuser réception", "resolve": "Résoudre", "details": "Détails de l'alerte" } },
            "ssh": { "console": { "title": "Console SSH", "subtitle": "Se connecter aux serveurs distants via SSH", "selectService": "Sélectionnez un service", "connect": "Connecter", "disconnect": "Déconnecter", "connected": "Connecté", "disconnected": "Déconnecté" }, "history": { "title": "Historique des commandes", "subtitle": "Suivre et examiner toutes les commandes SSH exécutées", "totalCommands": "Total des commandes", "successful": "Réussies", "failed": "Échouées", "services": "Services", "time": "Heure", "service": "Service", "user": "Utilisateur", "command": "Commande", "status": "Statut", "duration": "Durée", "noCommands": "Aucune commande ne correspond à vos filtres" }, "sftp": { "title": "Navigateur SFTP", "subtitle": "Parcourir et gérer les fichiers sur les serveurs distants", "server": "Serveur", "username": "Nom d'utilisateur", "password": "Mot de passe", "connect": "Connecter", "disconnect": "Déconnecter", "connected": "Connecté", "name": "Nom", "size": "Taille", "modified": "Modifié", "permissions": "Autorisations", "actions": "Actions", "download": "Télécharger", "delete": "Supprimer" } },
            "rdp": { "sessions": { "title": "Sessions RDP", "subtitle": "Lancer et gérer les connexions Remote Desktop Protocol", "newConnection": "Nouvelle connexion RDP", "server": "Serveur", "username": "Nom d'utilisateur", "password": "Mot de passe", "resolution": "Résolution", "colorDepth": "Profondeur de couleur", "connect": "Connecter", "download": "Télécharger le fichier .rdp", "activeSessions": "Sessions actives", "noSessions": "Aucune session RDP active", "user": "Utilisateur", "duration": "Durée", "disconnect": "Déconnecter", "connected": "Connecté" }, "recordings": { "title": "Enregistrements d'écran", "subtitle": "Afficher et gérer les sessions RDP enregistrées", "totalRecordings": "Total des enregistrements", "totalDuration": "Durée totale", "storageUsed": "Stockage utilisé", "session": "Session", "service": "Service", "dateTime": "Date et heure", "duration": "Durée", "size": "Taille", "actions": "Actions", "play": "Lire", "download": "Télécharger", "delete": "Supprimer", "noRecordings": "Aucun enregistrement ne correspond à vos filtres" } },
            "common": { "online": "En ligne", "offline": "Hors ligne", "loading": "Chargement...", "save": "Enregistrer", "cancel": "Annuler", "delete": "Supprimer", "edit": "Modifier", "search": "Rechercher", "filter": "Filtrer", "actions": "Actions", "status": "Statut", "name": "Nom", "close": "Fermer", "success": "Succès", "error": "Erreur", "warning": "Avertissement", "info": "Info" }
        }
    },
    nl: {
        translation: {
            "sidebar": { "dashboard": "Dashboard", "services": "Diensten", "docker": "Docker Beheer", "monitoring": "Monitoring", "terminal": "SSH Terminal", "rdp": "RDP Starter", "topology": "Bedrijfscentrum", "appStore": "App Store", "settings": "Instellingen", "logout": "Uitloggen" },
            "login": { "welcome": "Welkom Terug", "subtitle": "Log in om door te gaan", "username": "Gebruikersnaam", "password": "Wachtwoord", "signin": "Inloggen" },
            "dashboard": { "overview": { "title": "Dashboard Overzicht", "subtitle": "Monitor uw infrastructuur in één oogopslag", "serviceStatus": "Service Status", "totalServices": "Totaal Diensten", "online": "Online", "offline": "Offline", "alerts": "Waarschuwingen", "critical": "Kritiek", "warnings": "Waarschuwingen", "recentAlerts": "Recente Waarschuwingen", "viewAll": "Bekijk Alle Waarschuwingen", "uptime": "Systeem Uptime", "trend": "Trend" }, "favorites": { "title": "Favoriete Diensten", "subtitle": "Snelle toegang tot uw vastgezette diensten", "empty": "Nog geen favoriete diensten", "emptyHint": "Markeer diensten vanaf de Diensten pagina" } },
            "docker": { "title": "Docker Beheer", "subtitle": "Beheer Docker containers en diensten", "daemon": "Docker Daemon", "status": "Status", "running": "Actief", "stopped": "Gestopt", "containers": "Containers", "images": "Images", "version": "Versie", "notDetected": "Docker Niet Gedetecteerd", "notDetectedMsg": "Docker Engine draait niet of is niet geïnstalleerd", "retry": "Opnieuw Verbinden", "actions": { "start": "Starten", "stop": "Stoppen", "restart": "Herstarten", "logs": "Logs Bekijken" }, "logsTitle": "Container Logs" },
            "monitoring": { "metrics": { "title": "Historische Metrieken", "subtitle": "Bekijk serviceprestaties in de tijd", "selectService": "Selecteer een dienst", "dateRange": "Datumbereik", "last24h": "Laatste 24 Uur", "last7d": "Laatste 7 Dagen", "last30d": "Laatste 30 Dagen", "avgResponseTime": "Gem. Responstijd", "minResponseTime": "Min. Responstijd", "maxResponseTime": "Max. Responstijd", "uptimePercentage": "Uptime", "dataPoints": "Datapunten", "responseTime": "Responstijd", "availability": "Beschikbaarheidsstatus" }, "alerts": { "title": "Waarschuwingslog", "subtitle": "Monitor en beheer systeemwaarschuwingen", "severity": "Ernst", "status": "Status", "all": "Alles", "critical": "Kritiek", "warning": "Waarschuwing", "info": "Info", "active": "Actief", "resolved": "Opgelost", "search": "Zoek waarschuwingen...", "totalAlerts": "Totaal Waarschuwingen", "criticalAlerts": "Kritiek", "warningAlerts": "Waarschuwingen", "activeAlerts": "Actief", "resolvedAlerts": "Opgelost", "acknowledge": "Bevestigen", "resolve": "Oplossen", "details": "Waarschuwingsdetails" } },
            "ssh": { "console": { "title": "SSH Console", "subtitle": "Verbind met externe servers via SSH", "selectService": "Selecteer een dienst", "connect": "Verbinden", "disconnect": "Verbreken", "connected": "Verbonden", "disconnected": "Niet Verbonden" }, "history": { "title": "Commando Geschiedenis", "subtitle": "Track en bekijk alle uitgevoerde SSH commando's", "totalCommands": "Totaal Commando's", "successful": "Succesvol", "failed": "Mislukt", "services": "Diensten", "time": "Tijd", "service": "Dienst", "user": "Gebruiker", "command": "Commando", "status": "Status", "duration": "Duur", "noCommands": "Geen commando's komen overeen met uw filters" }, "sftp": { "title": "SFTP Browser", "subtitle": "Blader en beheer bestanden op externe servers", "server": "Server", "username": "Gebruikersnaam", "password": "Wachtwoord", "connect": "Verbinden", "disconnect": "Verbreken", "connected": "Verbonden", "name": "Naam", "size": "Grootte", "modified": "Gewijzigd", "permissions": "Rechten", "actions": "Acties", "download": "Downloaden", "delete": "Verwijderen" } },
            "rdp": { "sessions": { "title": "RDP Sessies", "subtitle": "Start en beheer Remote Desktop Protocol verbindingen", "newConnection": "Nieuwe RDP Verbinding", "server": "Server", "username": "Gebruikersnaam", "password": "Wachtwoord", "resolution": "Resolutie", "colorDepth": "Kleurdiepte", "connect": "Verbinden", "download": "Download .rdp Bestand", "activeSessions": "Actieve Sessies", "noSessions": "Geen actieve RDP sessies", "user": "Gebruiker", "duration": "Duur", "disconnect": "Verbreken", "connected": "Verbonden" }, "recordings": { "title": "Schermopnames", "subtitle": "Bekijk en beheer opgenomen RDP sessies", "totalRecordings": "Totaal Opnames", "totalDuration": "Totale Duur", "storageUsed": "Gebruikte Opslag", "session": "Sessie", "service": "Dienst", "dateTime": "Datum & Tijd", "duration": "Duur", "size": "Grootte", "actions": "Acties", "play": "Afspelen", "download": "Downloaden", "delete": "Verwijderen", "noRecordings": "Geen opnames komen overeen met uw filters" } },
            "common": { "online": "Online", "offline": "Offline", "loading": "Laden...", "save": "Opslaan", "cancel": "Annuleren", "delete": "Verwijderen", "edit": "Bewerken", "search": "Zoeken", "filter": "Filteren", "actions": "Acties", "status": "Status", "name": "Naam", "close": "Sluiten", "success": "Succes", "error": "Fout", "warning": "Waarschuwing", "info": "Info" }
        }
    },
    ko: {
        translation: {
            "sidebar": { "dashboard": "대시보드", "services": "서비스", "docker": "Docker 관리자", "monitoring": "모니터링", "terminal": "SSH 터미널", "rdp": "RDP 실행기", "topology": "운영 센터", "appStore": "앱 스토어", "settings": "설정", "logout": "로그아웃" },
            "login": { "welcome": "다시 오신 것을 환영합니다", "subtitle": "계속하려면 로그인하세요", "username": "사용자 이름", "password": "비밀번호", "signin": "로그인" },
            "dashboard": { "overview": { "title": "대시보드 개요", "subtitle": "인프라를 한눈에 모니터링하세요", "serviceStatus": "서비스 상태", "totalServices": "전체 서비스", "online": "온라인", "offline": "오프라인", "alerts": "알림", "critical": "심각", "warnings": "경고", "recentAlerts": "최근 알림", "viewAll": "모든 알림 보기", "uptime": "시스템 가동 시간", "trend": "추세" }, "favorites": { "title": "즐겨찾는 서비스", "subtitle": "고정된 서비스에 빠르게 액세스", "empty": "아직 즐겨찾는 서비스가 없습니다", "emptyHint": "서비스 페이지에서 서비스에 별표를 추가하세요" } },
            "docker": { "title": "Docker 관리자", "subtitle": "Docker 컨테이너 및 서비스 관리", "daemon": "Docker 데몬", "status": "상태", "running": "실행 중", "stopped": "중지됨", "containers": "컨테이너", "images": "이미지", "version": "버전", "notDetected": "Docker 감지되지 않음", "notDetectedMsg": "Docker 엔진이 실행되지 않거나 설치되지 않음", "retry": "연결 재시도", "actions": { "start": "시작", "stop": "중지", "restart": "재시작", "logs": "로그 보기" }, "logsTitle": "컨테이너 로그" },
            "monitoring": { "metrics": { "title": "과거 메트릭", "subtitle": "시간에 따른 서비스 성능 보기", "selectService": "서비스 선택", "dateRange": "날짜 범위", "last24h": "지난 24시간", "last7d": "지난 7일", "last30d": "지난 30일", "avgResponseTime": "평균 응답 시간", "minResponseTime": "최소 응답 시간", "maxResponseTime": "최대 응답 시간", "uptimePercentage": "가동 시간", "dataPoints": "데이터 포인트", "responseTime": "응답 시간", "availability": "가용성 상태" }, "alerts": { "title": "알림 로그", "subtitle": "시스템 알림 모니터링 및 관리", "severity": "심각도", "status": "상태", "all": "전체", "critical": "심각", "warning": "경고", "info": "정보", "active": "활성", "resolved": "해결됨", "search": "알림 검색...", "totalAlerts": "전체 알림", "criticalAlerts": "심각", "warningAlerts": "경고", "activeAlerts": "활성", "resolvedAlerts": "해결됨", "acknowledge": "확인", "resolve": "해결", "details": "알림 세부정보" } },
            "ssh": { "console": { "title": "SSH 콘솔", "subtitle": "SSH를 통해 원격 서버에 연결", "selectService": "서비스 선택", "connect": "연결", "disconnect": "연결 해제", "connected": "연결됨", "disconnected": "연결 해제됨" }, "history": { "title": "명령 기록", "subtitle": "실행된 모든 SSH 명령 추적 및 검토", "totalCommands": "전체 명령", "successful": "성공", "failed": "실패", "services": "서비스", "time": "시간", "service": "서비스", "user": "사용자", "command": "명령", "status": "상태", "duration": "기간", "noCommands": "필터와 일치하는 명령이 없습니다" }, "sftp": { "title": "SFTP 브라우저", "subtitle": "원격 서버의 파일 탐색 및 관리", "server": "서버", "username": "사용자 이름", "password": "비밀번호", "connect": "연결", "disconnect": "연결 해제", "connected": "연결됨", "name": "이름", "size": "크기", "modified": "수정됨", "permissions": "권한", "actions": "작업", "download": "다운로드", "delete": "삭제" } },
            "rdp": { "sessions": { "title": "RDP 세션", "subtitle": "원격 데스크톱 프로토콜 연결 시작 및 관리", "newConnection": "새 RDP 연결", "server": "서버", "username": "사용자 이름", "password": "비밀번호", "resolution": "해상도", "colorDepth": "색 농도", "connect": "연결", "download": ".rdp 파일 다운로드", "activeSessions": "활성 세션", "noSessions": "활성 RDP 세션 없음", "user": "사용자", "duration": "기간", "disconnect": "연결 해제", "connected": "연결됨" }, "recordings": { "title": "화면 녹화", "subtitle": "녹화된 RDP 세션 보기 및 관리", "totalRecordings": "전체 녹화", "totalDuration": "전체 기간", "storageUsed": "사용된 저장소", "session": "세션", "service": "서비스", "dateTime": "날짜 및 시간", "duration": "기간", "size": "크기", "actions": "작업", "play": "재생", "download": "다운로드", "delete": "삭제", "noRecordings": "필터와 일치하는 녹화가 없습니다" } },
            "common": { "online": "온라인", "offline": "오프라인", "loading": "로딩 중...", "save": "저장", "cancel": "취소", "delete": "삭제", "edit": "편집", "search": "검색", "filter": "필터", "actions": "작업", "status": "상태", "name": "이름", "close": "닫기", "success": "성공", "error": "오류", "warning": "경고", "info": "정보" }
        }
    }
};

i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        resources,
        fallbackLng: 'en',
        supportedLngs: ['hi', 'en', 'ru', 'fr', 'nl', 'ko'],
        load: 'languageOnly',
        debug: false,
        detection: {
            order: ['localStorage', 'navigator', 'htmlTag'],
            caches: ['localStorage'],
            lookupLocalStorage: 'i18nextLng',
            htmlTag: document.documentElement,
        },
        interpolation: {
            escapeValue: false
        },
        react: {
            useSuspense: false
        },
        fallbackNS: 'translation',
        returnEmptyString: false,
        returnNull: false,
        saveMissing: process.env.NODE_ENV === 'development',
        missingKeyHandler: (lng, ns, key) => {
            if (process.env.NODE_ENV === 'development') {
                console.warn(`[i18n] Missing translation [${lng}]: ${key}`);
            }
        }
    });

i18n.on('languageChanged', (lng) => {
    document.documentElement.lang = lng;
    const rtlLanguages = ['ar', 'he', 'fa', 'ur'];
    const isRTL = rtlLanguages.includes(lng);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';

    if (process.env.NODE_ENV === 'development') {
        console.log('[i18n] Language changed to:', lng, '|', document.documentElement.dir.toUpperCase());
    }
});

if (i18n.language) {
    const rtlLanguages = ['ar', 'he', 'fa', 'ur'];
    const isRTL = rtlLanguages.includes(i18n.language);
    document.documentElement.lang = i18n.language;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
}

export default i18n;
